version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-rocketseat
    container_name: api-nodejs-rocketseat
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres-rocketseat
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-rocketseat
    volumes:
      - database-rocketseat:/bitnami/postgresql

volumes:
  database-rocketseat: